### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by AkkilMG** [AkkilMG/Feedback-bot#4]
# **Notice**

## Content
- If you want any extra features please write us in this issue. We would love to add it if its possible. 
- If you want to add some unique feature which could help users. It would be appreciative step. But, Do provide well defined info.
- If you need this code in other languages then do comment. I will add multi language support.
- Bla.. Bla.. Bla..

**Thank you ❤️**

## External Contact

- [Telegram](https://telegram.me/HeimanSupport)

**Comment by SurajMeena** [comment]
Hi @HeimanPictures, I used this feedback bot few months ago. Earlier DB URL and Log Channel URL fields were not there and I actually didn't want them as well. I took a git clone and I am not able to start the bot without filling in DB URL, etc. Can these parameters be made optional?

**Comment by HeimanPictures** [comment]
@SurajMeena oh! I will make non db branch

**Comment by HeimanPictures** [comment]
@SurajMeena There is a small issue as you won't be having broadcast I recommend you to go with https://github.com/HeimanPictures/Feedback-bot/releases/tag/v1.0.0 a old version. I hope it helped you, if any issue don't hesitate for help.

**Comment by vlab97** [comment]
Hi! Is it possible to implement sending a group of media in one message?  That is, without separation according to different messages?![image](https://user-images.githubusercontent.com/44323817/211202624-8ec61b0c-95d2-4425-9933-5c4a90fb64b2.jpeg)

**Comment by vlab97** [comment]
also interested in the parameter "OWNER_ID".  when using a private group ID, the bot does not work correctly.![image](https://user-images.githubusercontent.com/44323817/211203281-75257a65-7ad8-41e5-8e59-b3da807b3167.jpeg)
